on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.101.0'
      - name: Build
        run: hugo --minify
      - name: Publish French
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_USER_ID }}
          projectName: nkirchho-dev-fr # e.g. 'my-project'
          directory: public/fr # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish English
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_USER_ID }}
          projectName: nkirchho-dev-en # e.g. 'my-project'
          directory: public/en # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
